Thinks it is returning null when filtering out nulls in Laravel collection
bmitch/Codor pull request #152
Opened 2021-12-23 16:05 UTC by kevin-schmitt

see issue #130

2021-12-24 13:26 UTC, villfa requested changes
Thank you very much!
I just have a couple of remarks, but otherwise it looks good.

2021-12-24 13:26 UTC, villfa commented on src/Codor/Sniffs/Files/ReturnNullSniff.php
> +        $comparaisonIndex = key($semicolons) - 3;
Could replace `comparaison` by `comparison` and rename the files accordingly please?

2021-12-24 13:26 UTC, villfa commented on src/Codor/Sniffs/Files/ReturnNullSniff.php
> +        return (in_array($type, ['T_IS_NOT_IDENTICAL', 'T_IS_IDENTICAL']) == true);
```suggestion
        return in_array($type, ['T_IS_NOT_IDENTICAL', 'T_IS_IDENTICAL', 'T_IS_NOT_EQUAL', 'T_IS_EQUAL'], true) === true;
```

2021-12-25 11:55 UTC, kevin-schmitt commented
Thank you very much for you help and review @villfa .
Can you check and validate if is good please?

2021-12-25 11:59 UTC, villfa approved these changes

2021-12-25 22:49 UTC, merged

2021-12-25 22:50 UTC, villfa commented
Thanks :)